# color scheme based on https://github.com/morhetz/gruvbox

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir_writable dir rbenv vcs) # context dir rbenv vcs

POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="246"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="241"

POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="234"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="167"
POWERLEVEL9K_DIR_HOME_FOREGROUND="246"
POWERLEVEL9K_DIR_HOME_BACKGROUND="241"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="234"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="66"

POWERLEVEL9K_VCS_HIDE_TAGS=true
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="234"
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="142"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="234"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="214"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="234"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="142"
POWERLEVEL9K_VCS_ACTIONFORMAT_FOREGROUND='124'

#POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs time) # status root_indicator background_jobs history time

POWERLEVEL9K_STATUS_OK_FOREGROUND="142"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="234"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="167"

POWERLEVEL9K_HISTORY_FOREGROUND="246"
POWERLEVEL9K_HISTORY_BACKGROUND="239"

POWERLEVEL9K_TIME_FOREGROUND="246"
POWERLEVEL9K_TIME_BACKGROUND="241"
